blank_issues_enabled: false
contact_links:
  - name: Private security advisory
    url: https://github.com/{REPOSITORY_OWNER}/{REPOSITORY_NAME}/security/advisories/new
    about: Report vulnerabilities privately.
